apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-ogot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-ogot
    app.kubernetes.io/part-of: build-suite-test-application-dqhl
  name: test-component-pac-ogot
  namespace: build-e2e-jmpx-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-ogot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-ogot
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:6c2db448c932fc156f143d6b3f279592ef0cb96a568e43d1974ecc888d864b60
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
